CREATE TABLE `marcacao` (
  `nCdMarcacao` int(11) NOT NULL AUTO_INCREMENT,
  `nCdFuncionario` decimal(15,0) DEFAULT NULL,
  `dMarcacao` datetime DEFAULT NULL,
  `dEntrada1` time DEFAULT NULL,
  `nCdTpMarcacaoE1` int(11) DEFAULT NULL,
  `nCdOcorrenciaE1` int(11) DEFAULT NULL,
  `dSaida1` time DEFAULT NULL,
  `nCdTpMarcacaoS1` int(11) DEFAULT NULL,
  `nCdOcorrenciaS1` int(11) DEFAULT NULL,
  `dEntrada2` time DEFAULT NULL,
  `nCdTpMarcacaoE2` int(11) DEFAULT NULL,
  `nCdOcorrenciaE2` int(11) DEFAULT NULL,
  `dSaida2` time DEFAULT NULL,
  `nCdTpMarcacaoS2` int(11) DEFAULT NULL,
  `nCdOcorrenciaS2` int(11) DEFAULT NULL,
  `dEntrada3` time DEFAULT NULL,
  `nCdTpMarcacaoE3` int(11) DEFAULT NULL,
  `nCdOcorrenciaE3` int(11) DEFAULT NULL,
  `dSaida3` time DEFAULT NULL,
  `nCdTpMarcacaoS3` int(11) DEFAULT NULL,
  `nCdOcorrenciaS3` int(11) DEFAULT NULL,
  `dEntrada4` time DEFAULT NULL,
  `nCdTpMarcacaoE4` int(11) DEFAULT NULL,
  `nCdOcorrenciaE4` int(11) DEFAULT NULL,
  `dSaida4` time DEFAULT NULL,
  `nCdTpMarcacaoS4` int(11) DEFAULT NULL,
  `nCdOcorrenciaS4` int(11) DEFAULT NULL,
  PRIMARY KEY (`nCdMarcacao`),
  KEY `fk_marcacao_funcionario` (`nCdFuncionario`),
  KEY `fk_marcacao_nCdTpMarcacaoE1` (`nCdTpMarcacaoE1`),
  KEY `fk_marcacao_nCdTpMarcacaoE2` (`nCdTpMarcacaoE2`),
  KEY `fk_marcacao_nCdTpMarcacaoE3` (`nCdTpMarcacaoE3`),
  KEY `fk_marcacao_nCdTpMarcacaoE4` (`nCdTpMarcacaoE4`),
  KEY `fk_marcacao_nCdTpMarcacaoS1` (`nCdTpMarcacaoS1`),
  KEY `fk_marcacao_nCdTpMarcacaoS2` (`nCdTpMarcacaoS2`),
  KEY `fk_marcacao_nCdTpMarcacaoS3` (`nCdTpMarcacaoS3`),
  KEY `fk_marcacao_nCdTpMarcacaoS4` (`nCdTpMarcacaoS4`),
  KEY `fk_marcacao_nCdOcorrenciaE1` (`nCdOcorrenciaE1`),
  KEY `fk_marcacao_nCdOcorrenciaE2` (`nCdOcorrenciaE2`),
  KEY `fk_marcacao_nCdOcorrenciaE3` (`nCdOcorrenciaE3`),
  KEY `fk_marcacao_nCdOcorrenciaE4` (`nCdOcorrenciaE4`),
  KEY `fk_marcacao_nCdOcorrenciaS1` (`nCdOcorrenciaS1`),
  KEY `fk_marcacao_nCdOcorrenciaS2` (`nCdOcorrenciaS2`),
  KEY `fk_marcacao_nCdOcorrenciaS3` (`nCdOcorrenciaS3`),
  KEY `fk_marcacao_nCdOcorrenciaS4` (`nCdOcorrenciaS4`)
);
