CREATE TABLE `titulos` (
  `nCdBoleto` double NOT NULL AUTO_INCREMENT,
  `nNossoNumero` varchar(16) DEFAULT NULL,
  `nCdPessoa` decimal(14,0) DEFAULT NULL,
  `SeuNum` varchar(15) DEFAULT NULL,
  `dVcto` datetime DEFAULT NULL,
  `dEmissao` datetime DEFAULT NULL,
  `nVlrTitulo` double DEFAULT NULL,
  `nVlrJuros` double DEFAULT NULL,
  `dDesconto` datetime DEFAULT NULL,
  `nVlrDesconto` double DEFAULT NULL,
  `dMulta` datetime DEFAULT NULL,
  `nVlrMulta` double DEFAULT NULL,
  `CodOcorRetorno` varchar(2) DEFAULT NULL,
  `CodBarras` varchar(50) DEFAULT NULL,
  `cMensagem1` varchar(255) DEFAULT NULL,
  `cMensagem2` varchar(255) DEFAULT NULL,
  `cMensagem3` varchar(255) DEFAULT NULL,
  `cMensagem4` varchar(255) DEFAULT NULL,
  `cMensagem5` varchar(255) DEFAULT NULL,
  `cMensagem6` varchar(255) DEFAULT NULL,
  `cLinhaDigitavel` varchar(50) DEFAULT NULL,
  `TipDtOcorrencia` datetime DEFAULT NULL,
  `dPgto` datetime DEFAULT NULL,
  `nVlrPago` double DEFAULT NULL,
  `nVlrDesEf` double DEFAULT NULL,
  `nVlrAcrEf` double DEFAULT NULL,
  `nVlrAbaEf` double DEFAULT NULL,
  `nVlrJurEf` double DEFAULT NULL,
  `nVlrMulEf` double DEFAULT NULL,
  `nVlrCredEf` double DEFAULT NULL,
  `nVlrTarEf` double DEFAULT NULL,
  `dCredef` datetime DEFAULT NULL,
  `dTarief` datetime DEFAULT NULL,
  `nCdCanalPgto` varchar(2) DEFAULT NULL,
  `nCdFormaPgto` varchar(2) DEFAULT NULL,
  `nCdFloatPgto` varchar(2) DEFAULT NULL,
  `nCdAcordo` int(11) DEFAULT NULL,
  `cId` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`nCdBoleto`),
  KEY `ix_titulo_cpf` (`nCdPessoa`),
  KEY `ix_nossonumero` (`nNossoNumero`),
  KEY `Fk_titulos_Acordo` (`nCdAcordo`)
)
